import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const gaId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {gaId !== undefined && <GoogleAnalytics gaId={gaId} />}
      <body>{children}</body>
    </html>
  )
}
