# fly.toml app configuration file generated for tgymfr-website on 2024-01-05T15:21:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tgymfr-website"
primary_region = "cdg"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
