# fly.toml app configuration file generated for tgymfr-app on 2024-01-05T15:22:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tgymfr-app"
primary_region = "cdg"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
